### ISSUE TITLE
Could this be made to work with MSFS2020?

### ISSUE THREAD

**Issue by dbackeus** [marcosox/fsx-saas#2]
I understand that Microsoft Flight Simulator 2020 is also exposing a SimConnect API. However attempting to run fsx-saas (whether MSFS2020 is running or not) I get the following error:

```
java -jar .\fsx-saas-1.2.0-fat.jar
Welcome to FSX simconnect as a service version 1.2.0
MainVerticle.start()
[]
java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(Unknown Source)
        at java.net.InetSocketAddress.<init>(Unknown Source)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:184)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:217)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:106)
        at io.github.marcosox.fsxsaas.fsx.FSX.startSimConnect(FSX.java:49)
        at io.github.marcosox.fsxsaas.fsx.FSX.<init>(FSX.java:32)
        at io.github.marcosox.fsxsaas.MainVerticle.setup(MainVerticle.java:212)
        at io.github.marcosox.fsxsaas.MainVerticle.start(MainVerticle.java:40)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Sep 06, 2020 2:37:22 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(Unknown Source)
        at java.net.InetSocketAddress.<init>(Unknown Source)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:184)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:217)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:106)
        at io.github.marcosox.fsxsaas.fsx.FSX.startSimConnect(FSX.java:49)
        at io.github.marcosox.fsxsaas.fsx.FSX.<init>(FSX.java:32)
        at io.github.marcosox.fsxsaas.MainVerticle.setup(MainVerticle.java:212)
        at io.github.marcosox.fsxsaas.MainVerticle.start(MainVerticle.java:40)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(Unknown Source)
        at java.net.InetSocketAddress.<init>(Unknown Source)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:184)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:217)
        at flightsim.simconnect.SimConnect.<init>(SimConnect.java:106)
        at io.github.marcosox.fsxsaas.fsx.FSX.startSimConnect(FSX.java:49)
        at io.github.marcosox.fsxsaas.fsx.FSX.<init>(FSX.java:32)
        at io.github.marcosox.fsxsaas.MainVerticle.setup(MainVerticle.java:212)
        at io.github.marcosox.fsxsaas.MainVerticle.start(MainVerticle.java:40)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
```

Since I don't actually own FSX I can't confirm if the error is with the MSFS2020 integration or something else in how I'm running the app.

**Comment by marcosox** [comment]
I don't (and won't in the near future) own a copy of MSFS2020 to check this, but with in FSX [there is a `simconnect.cfg` file that controls the connection parameters.](https://docs.microsoft.com/en-us/previous-versions/microsoft-esp/cc526983(v=msdn.10)#the-simconnectcfg-file) You probably need to set/tweak that.
